spring.application.name=speak-check

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.maximum-pool-size=5

app.jwt.secret =${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

app.s3.endpoint=${RAILWAY_S3_ENDPOINT}
app.s3.bucket=${RAILWAY_S3_BUCKET}
app.s3.accessKey=${RAILWAY_S3_ACCESS_KEY}
app.s3.secretKey=${RAILWAY_S3_SECRET_KEY}
app.s3.region=${RAILWAY_S3_REGION}